# Data configuration
dataset: null   # Required field
negative_ratio_train: 1.0
negative_ratio_val: 2.0
num_workers: 4

# Model configuration - Vision Transformer architecture
img_size: 224
patch_size: 16
in_channels: 3
embed_dim: 384
depth: 6
n_heads: 6
mlp_ratio: 4.0
dropout: 0.1
feature_dim: 256

# Training configuration
batch_size: 16
val_batch_size: 32
learning_rate: 1e-4
weight_decay: 1e-4
num_epochs: 50
patience: 5
min_delta: 0.002

# Loss configuration
loss_margin: 1.0
loss_alpha: 0.7

# Device configuration
device: null